version: '2'

services:
  jenkins:
    container_name: jenkins
    hostname: jenkins
    build:
      context: ./
      args:
        version: lts
        extra_packages: "net-tools"
        http_port: 8083
        slave_port: 8084
        plugins: ""
    restart: always
    ports:
      - "8083:8083"    # http port
      - "8084:8084"    # slave port
