version: '2'

services:
  jenkins:
    container_name: jenkins
    hostname: jenkins
    build:
      context: ./
      args:
        version: lts
        admin_username: "admin"
        admin_password: "password"
        http_port: 8083
        slave_port: 8084
        extra_packages: "build-essential gcc g++"
        plugins: "git mailer git-parameter build-timeout rebuilder"
    restart: always
    ports:
      - "8083:8083"    # http port
